<?
	$page->title = "Terms of Use | nuvoTV Official Site";
	$page->template = "standard";
	$page->bodyClasses[] = "layout-full";
		
	$page->components["hero"] = <<<EOHERO
	<div class="title">
		<!-- <img src="/assets/images/titles/terms-of-use.png" alt="Privacy Policy" /> -->
		<h1 class="title">Privacy Policy</h1>
	</div>
EOHERO;

	$page->components["content"] = <<<EOCONTENT
<div class="content"><p><br />
<br />
NuvoTV has created this privacy policy in order to demonstrate our firm commitment to the privacy of our guests. The following discloses our information gathering and dissemination practices for MYNUVOTV.COM, and any other website under which we conduct business. We maintain reasonable physical, electronic and procedural safeguards to protect your personally identifiable information and, while no data transmission over the Internet is 100% secure from intrusion, we have used and will continue to use commercially reasonable efforts to ensure the protection of the information you provide to us.<br />
<br />
The nuvoTV Privacy Policy is a part of the terms and conditions which are set forth in our Terms of Use. Any terms that are not defined in the nuvoTV Privacy Policy shall have the meaning given in our Terms of Use. Both the <b>nuvoTV Privacy Policy</b> and Terms of Use Agreement are legally binding on all users.<br />
<br />
<b>YOUR CALIFORNIA PRIVACY RIGHTS</b><br />
If you are a resident of the State of California, under the California Civil Code, you have the right to request from companies conducting business in California a list of all third parties to which the company has disclosed personally identifiable information during the preceding year for direct marketing purposes. Alternatively, the law provides that if a company has a privacy policy that gives either an opt-out (which we may sometimes refer to as &quot;unsubscribe&quot;) or opt-in choice for use of your personally identifiable information by third parties (such as advertisers or affiliated companies) for marketing purposes, the company may instead provide you with information on how to exercise your disclosure choice options.<br />

<br />
NuvoTV qualifies for the alternative option; it has a comprehensive privacy policy and provides you with details on how you may either opt-out or opt-in to the use of your personally identifiable information by third parties for direct marketing purposes. Therefore, we are not required to maintain or disclose a list of the third parties that received your personally identifiable information for marketing purposes during the preceding year.<br />
<br />
If you are a California resident and request information about how to exercise your third party disclosure choices you must send a request via regular mail, along with a postage paid self-addressed return envelope (including your name, street address, city, state, and zip code) to the following address:<br />
<br />
<b> S&Iacute; TV, Inc.<br />
700 N Central Ave<br />
Glendale, CA 91203<br />
Attn: Your California Privacy Rights<br />

c/o Privacy Administrator<br />
<br />
All requests sent via regular mail must be labeled &quot;Your California Privacy Rights&quot; on the envelope and clearly stated on the actual request. We will not accept requests via the telephone or by facsimile.</b> We are not responsible for notices that are not labeled or sent properly, or do not have complete information.<br />
<br />
<b>YOUR ACCEPTANCE OF THESE TERMS / MODIFICATION</b>S<br />
By using this website, you indicate your acceptance of all terms of the nuvoTV Privacy Policy. If you do not agree to this policy, please discontinue use of our websites. Your continued use of any nuvoTV website following the posting of changes to these terms indicates your acceptance of those changes. We reserve the right to revise this Privacy Policy at any time by updating this posting without advance notice to you. Such revisions shall be effective immediately upon posting.<br />
<br />

<b>A Special Note about Children</b><br />
Children under the age of 13 are not eligible to use our services, and we ask that such persons not submit personal information to us. We believe that is important that parents supervise their children when they are online. As a result, we ask that children under the age of 18 use this service only in conjunction with parents or guardians. In addition, our services are offered to residents of the United States of America, its territories and possessions. If you are not a United States resident, please discontinue use of our websites immediately<br />
<br />
<b>USE OF IP ADDRESSES</b><br />
An IP address is a number which is assigned to your computer when you are online. Web servers identify your computer by its IP address. NuvoTV collects IP addresses for the purposes of system administration, to report aggregate information to our advertisers, and to audit the use of our site. When our guests request pages from nuvoTV websites, our servers log the guests' IP addresses. We do not normally link IP addresses to anything personally identifiable, which means that a user's session will be logged, but the user remains anonymous to nuvoTV and other users. We will use IP addresses to identify a user when we feel it is necessary to enforce compliance with our Terms of Use or to protect our service, site, customers, or others. Please review each service prior to use and only use those that disclose information which you are willing to disclose.<br />
<br />
<b>USE OF COOKIES</b><br />
Cookies are pieces of information that a Website transfers to your computer for record-keeping purposes. Cookies make browsing the Internet easier for you by saving your preferences while you access a Website. NuvoTV never saves passwords in cookies. By showing how and when users use a website, cookies help us see which areas are popular and which are not. Many improvements and updates to the nuvoTV web content are based on such data as total number of visitors and pages viewed. This information is most easily tracked with cookies. We use the information from cookies to provide services better tailored to our users' needs. NuvoTV uses cookies primarily in two ways. First, we use them to specify unique preferences so that you do not have to tell us repeatedly about the content you are interested in. Secondly, we use cookies to track user trends and patterns, so we can improve areas of the nuvoTV online experience that our users find valuable. While both of these activities depend on the use of a cookie, visitors to nuvoTV always have the option of disabling cookies via their browser preferences. Most browsers are initially set up to accept cookies. You can reset your browser to refuse all cookies or indicate when a cookie is being sent. Please note that some parts of the nuvoTV service may not function properly or may be considerably slower if you refuse cookies. For example, you may have difficulty entering contests, or playing games. You may occasionally get cookies directly from our advertisers. NuvoTV does not control these cookies.<br />
<br />
<b>Other Information We Collect and Our Use and Disclosure of Your Information</b><br />

Our website's registration form requires you to provide your date of birth (for age verification purposes), create a password, and provide certain contact information (including your name and email address). Information about your gender, address, zip code, phone number and income is optional. The customer's contact information is used to contact the visitor when necessary in the day to day running of the website. Additional information may be collected in connection with certain games, promotions, sweepstakes and contests.<br />
<br />
We also occasionally send emails and newsletters to our users, announcing special promotions changes in our services, and other information we believe will be of interest to our users. Users may opt-out of receiving future mailings; see the choice/opt-out section below. Demographic and profile data is also collected at our site. This information may be shared with advertisers and our partners on an individual or aggregate basis.<br />
<br />
If you send us personal correspondence, such as emails or letters, or if other users or third parties send us correspondence about your activities or postings on our site, we may collect such information into a file specific to you. We would use information in the file that we maintain for you, and other information that we obtain from your use of the services, to resolve disputes, troubleshoot problems and enforce our Terms of Use. <br />
<br />
We have partnered with various companies, and gather information regarding items and products our partners may provide. This information may be made available to those companies on an individual or aggregate basis. <br />
<br />
Certain contests and sweepstakes sponsored by us will require a separate registration process in which you may be required to submit your first and last name, street address, city, state and zip code, email address, telephone number and date of birth. Additional personally identifiable information may also be requested depending on the specific contest or promotion, but submission of such information may be optional. The entry page, submission form and/or Rules of the contest/promotion will provide the specific requirements. You may also have the opportunity to opt-in to special contests, promotions or offers from our advertisers in connection with many of these types of contests and promotions. <br />
<br />
We cannot ensure that all of your private communications and other personally identifiable information will never be disclosed in ways not otherwise described in this Privacy Policy. For example, we may be forced to disclose information to the government or third parties under certain circumstances, or third parties may unlawfully intercept or access transmissions or private communications. We can (and you authorize us to) disclose any information about you to law enforcement or other government officials as we, in our sole discretion, believe necessary or appropriate in connection with an investigation of fraud, intellectual property infringements, or other activity that is illegal or may expose us to legal liability. <br />

<br />
<b>Linked Sites</b><br />
For your convenience, this website contains links to other websites. NuvoTV is not responsible for the privacy practices or the content of such websites. Users should be aware that when they are on MYNUVOTV.com, they could be directed to other sites that are beyond our control. There are links to other sites from nuvoTV pages that take you outside our service. For example, if you click on a banner advertisement, doing so may direct you off of MYNUVOTV.COM. Such other sites may send their own cookies to users, collect data, or solicit personal information. Whenever you give out personal information online (for example, via message boards or chat rooms) information can be collected and used by other people. While nuvoTV strives to protect our users' personal information and privacy, we cannot guarantee the security of any information you disclose online, and you do so at your own risk. <br />
<br />
<b>Security</b><br />
This site has security measures in place to protect the loss, misuse and alteration of the information under our control. All user information is stored on a server operated by a third party, using standard security measures. Notwithstanding these efforts, we caution you that &quot;perfect security&quot; does not exist on the Internet and therefore you share information at your own risk.<br />
<br />
<b>Postings</b><br />
Your comments, suggestions and information are important to us. Portions of this website may provide you and other users an opportunity to submit, post, display, transmit and/or exchange information, ideas, opinions, photographs, images, video, creative works or other information, messages, transmissions or material to us, to the nuvoTV websites or to other users (&quot;Post&quot; or &quot;Postings&quot;). You understand, acknowledge and agree that such Postings are the sole responsibility of the person from whom such Postings originate. This means that you, the user, and not the nuvoTV websites, are entirely responsible for the consequences of all Postings that you upload, post, email, transmit or otherwise make available via our websites and services. Postings do not reflect the views of nuvoTV, any of its affiliated or related partners or companies, or any of their respective websites or services. We do not always monitor, endorse, edit or screen any Postings, although we reserve the right to do so, nor shall we be liable for any Posting that is in violation of this Privacy Policy. In no event shall nuvoTV, any of its affiliated or related partners or companies, or any of their respective websites or services have or be construed to have any responsibility or liability for or in connection with any Posting whatsoever; however, if we determine, in our sole discretion and judgment, that any Posting does or may violate any of the terms of this Privacy Policy, we reserve the right, at any time and without limiting any and all other rights we may have under this Privacy Policy, at law or in equity, to: (a) refuse to allow you to Post; (b) remove and delete Postings; (c) revoke your right to use any of the nuvoTV websites or services; and/or (d) use any technological, legal, operational or other means available to us to enforce the provisions of this Privacy Policy, including, without limitation, blocking specific IP addresses or deactivating your registration our websites.<br />

<br />
If a Posting originates from you or your account, you hereby agree that: (a) you are placing the Posting in the public domain without reservation of any rights or further control over the Posting or its use and you specifically authorize nuvoTV, its affiliated or related partners and companies to use such Posting in whole or in part, throughout the universe, in perpetuity in or on any and all media, now known or hereafter devised, and alone or together or as part of other information, content and/or material of any kind or nature; (b) you represent and warrant that (i) the Posting is original to you or fully cleared for use as contemplated herein, (ii) the Posting does and will not, in any way, violate or breach any of the terms of this Privacy Policy, (iii) the Posting does not contain libelous, tortious, or otherwise unlawful information, infringe or violate any copyright or other right, or contain any matter the publication or sale of which will violate any federal or state statute or regulation, (iv) the Posting is not obscene or in any other manner unlawful, (v) the Posting shall not be injurious to the health of the user, and (vi) we shall not be required to pay or incur any sums to any person or entity as a result of our use or exploitation of the Posting; (c) if your Posting incorporates the name, logo, brand, service or trademark, voice, likeness or image of any person, firm or enterprise, you specifically represent and warrant that you have the right to place such Posting in the public domain and grant nuvoTV the right to use such Posting as described above; (d) we have the right to delete, re-format and/or change your Posting in any manner that we may determine (although you will not be responsible for any such changes made); and (e) you will not be entitled to any compensation because of the use or exploitation by us or any third party of any videos and other Postings you make to us or any ideas or concepts contained therein, and the submission of a video or other Posting, and/or any posting or display thereof, is not any admission of novelty, priority or originality. Even if you subsequently see or learn of a presentation, motion picture, still photograph, film, video or any other content which appears to incorporate any idea or concept or include anything similar or identical to that contained in any video or other Posting that you or anyone else submits to or through the Site, you acknowledge and agree that you shall not be entitled to any compensation therefore.<br />
<br />
The amount of storage space on our websites per user is limited. Some Postings may not be processed due to space constraints or outbound message limitations. You understand, acknowledge and agree that we assume no responsibility for deletion of Postings or any failure to store, receive or deliver Postings in a timely manner or any other matter relating to Postings.<br />
<br />
Posting is for noncommercial purposes only and you may not Post in any manner which does or is intended to promote or generate revenue for any business enterprise or commercial activity.<br />
<br />
<b>Choice/Opt-Out</b><br />
This website gives users the following options for removing their information from our database to not receive future communications or to no longer receive our service. To keep you in control of your personal information and the communications directed to you, we allow you to opt out of the following services: receiving communications (including our newsletters) from us about new nuvoTV shows, and receiving communications about offers from third-party companies that offer a product or service that we think would be of value to you. If you object to such use for any reason, you may stop that use by modifying your member information online.<br />
1. Change your mailing preferences at My Account <br />
<b>Correct/Update</b><br />

This site gives users the following options for changing and modifying information previously provided.<br />
1. Visit My Account<br />
<b>Contacting nuvoTV about the Website</b><br />
If you have any questions about this privacy policy, the practices of this site, or your dealings with nuvoTV or this Website, you can contact:<br />
S&Iacute; TV, Inc.<br />
700 N Central Ave.<br />
Glendale, CA 91203<br />
E-mail: <a href="mailto:webmaster@mynuvotv.com">webmaster@mynuvotv.com</a><br />

rev date: 10.15.2007<br />
<br />
</div>
EOCONTENT;


/*

	$page->components["content"] = <<<EOCONTENT
	<div class="main white-box">
            	<h1 class="title">Terms of Use</h1>
		        			    	      <div class="node">
            <span class="submitted"></span>
    <div class="content"><p><b>1. ACCEPTANCE OF TERMS</b><br>
The following terms and conditions are a legal agreement (the "Agreement") between you and S&Iacute; TV, Inc. ("nuvoTV") with regard to your use of the website located at <a title="www.mynuvotv.com" href="http://www.mynuvotv.com/">MYNUVOTV.COM</a> and any other sites operated by nuvoTV. Please read the Agreement carefully. By using the nuvoTV website, you understand, acknowledge and agree that you will abide by this Agreement. The term "Agreement" includes these Terms and Conditions of Use, together with any other terms posted on the website, including the nuvoTV Privacy Policy, the nuvoTV User Content Submission Agreement, and any terms or rules which apply to your participation in promotions, contests, sweepstakes, etc. . All of these other documents are hereby incorporated into this Agreement by this reference. As described in more detail below, this Agreement does not address the terms applicable to any third party content or any websites or links that may direct you to third party websites or web pages.</p>

<p><b>2. USER AGE REQUIREMENTS </b><br>
The nuvoTV website is offered and made available only to users 13 years of age or older, and if you are not at least 13 years old, or your use of our nuvoTV website is prohibited or restricted in any way by the laws of the jurisdiction from which you are accessing the website, or if you do not agree to all of the terms of the Agreement, you must cease using the nuvoTV website immediately because by using or attempting to use the nuvoTV website, you certify that you are at least 13 years of age and meet all other eligibility requirements for your use of the nuvoTV website. To complete the registration process, you must provide your true and correct date of birth.</p>

<p>The nuvoTV website contains material that may not be appropriate for children. If there is a concern by parents that children may visit this site, we recommend using a parental control software package. Some sample parental software packages include: Net Nanny, Cyber Patrol and Cybersitter. Please be advised that we do not endorse any one parental software package. While no parental software package replaces careful supervision of Internet use by children, these tools can be a useful addition to your suite of Internet applications. Please read the nuvoTV Privacy Policy , in particular as it pertains to children under the age of 13.</p>

<p><b>3. REGISTRATION </b><br>
Certain parts of the nuvoTV website are available to all users without the need to register. You may access those pages and features without registering; provided, however, we reserve the right to make changes, limit or restrict those pages and features at any time in our discretion, without notice to you. In order to access and use certain services, features or functions of the nuvoTV website, such as our Forums, our user content submission service, and any interactive feature of the nuvoTV website, you must register. As part of the registration process, you will need to select and provide us with a unique user name and choose a password which must form a unique combination (a "User ID"), and we also request that you provide your e-mail address, and may request that you provide other information as we may require. We may also provide users with additional codes or passwords necessary to access and use certain services, features or functions of the nuvoTV website. Please read the nuvoTV Privacy Policy, which describes the non-public, personally identifiable information ("Personal Information") we collect, use, disclose, manage and store. Your User ID is personal to you and you must not allow any others to use your User ID under any circumstances. nuvoTV disclaims any and all liability for any damages caused by theft or disclosure of your User ID. Do not disclose or authorize anyone else to use your User ID. You agree to immediately notify us if you become aware of or believe there is or may have been any unauthorized use of your User ID or any other need to cancel your User ID for security reasons.</p>

<p><b>4. MODIFICATIONS</b> <br>
nuvoTV retains the right to change the terms of this Agreement at any time in its sole discretion. We will post or display notices of material changes on the nuvoTV website. Once posted, such changes become effective immediately, and if you use the nuvoTV website after they become effective, you thereby agree to be bound by the changes. You should check back frequently and review this Agreement regularly so you are aware of the most current rights and obligations that apply to you. nuvoTV retains the right to change, modify, withdraw, suspend or even permanently discontinue all or any portions of the nuvoTV website at any time, without any liability or obligation to you, with or without notice.</p>

<p><b>5. PRIVACY</b> <br>
We respect your privacy and the use and protection of your Personal Information. Please see our nuvoTV Privacy Policy for important information and disclosures relating to the collection and use of your Personal Information in connection with your use of the nuvoTV website. If you have any questions regarding nuvoTV's privacy practices, you may send your question to us by e-mail to <a href="mailto:feedback@mynuvotv.com">feedback@mynuvotv.com</a> or by U.S. mail to S&Iacute; TV, Inc., Attn: Webmaster, 3030 Andrita Street, Los Angeles, California 90065.</p>

<p><b>6. USE OF MATERIAL </b><br>
The nuvoTV website, including but not limited to all content, show information, media and materials, website code, design, text, images, photographs, illustrations, audio and video material, media files, art, graphics, articles, databases, proprietary information, writings, spoken statements, music, video recordings, audio-visual works and recordings, slides, portraits, animated and/or motion pictures, caricatures, likenesses, vocal or other sounds, sound recordings, voices, voice reproductions, computer graphics and visual effects, as well as any associated documentation, and all copyrightable or otherwise legally protectible elements of the nuvoTV website, including, without limitation, the selection, sequence and 'look and feel' and arrangement of items, and all derivative works, translations, adaptations or variations of same, regardless of the medium, broadcast medium, format or form, now known or hereinafter developed or discovered, and regardless of where produced, on location, in a studio or elsewhere, characters, real or imaginary, in any part of the world, are the property of nuvoTV and/or its Affiliates, and their Advertisers, licensors, suppliers, service providers, promotional partners and/or sponsors (all of the foregoing, individually and/or collectively, is referred to herein as "nuvoTV Materials"). The nuvoTV Materials are legally protected, without limitation, under U.S. Federal and State, as well as applicable foreign laws, regulations and treaties.</p>

<p>nuvoTV authorizes you to access the nuvoTV Materials and grants you the right to use the nuvoTV website solely for your non-commercial, non-exclusive, non-assignable, non-transferable and limited personal use and for no other purpose whatsoever. You must not alter, delete or conceal any copyright or other notices contained on the nuvoTV website, including notices on any nuvoTV Materials you download, transmit, display, print or reproduce from the nuvoTV website. Unless we explicitly and specifically notify you otherwise in writing, you shall not, nor will you allow any third party to reproduce, modify, create derivative works from, display, perform, publish, distribute, sell, upload, transmit, disseminate, broadcast or circulate to any third party (including, without limitation, on or via a third party website) or otherwise use, any nuvoTV Materials without the express prior written consent of nuvoTV. Any unauthorized or prohibited use of any nuvoTV Materials, including use in contravention of this Agreement, may subject you to civil liability, criminal prosecution, or both. All content submitted by users registered to use our user content submission service are subject to our <b>nuvoTV User Content Submission Agreement</b>.</p>

<p>You may not use any computerized or automatic mechanism, including without limitation, any web spider or robot, to access, extract or download any nuvoTV Materials from the nuvoTV website. You hereby warrant to nuvoTV that you will not use the nuvoTV website for any unlawful purpose or purpose prohibited by this Agreement. If you violate any term of this Agreement, your permission to use the nuvoTV Materials automatically terminates and you must immediately cease all use thereof and destroy any copies you have made of any of the nuvoTV Materials. You are solely responsible for complying with all import and export laws and regulations and all applicable laws of any jurisdiction inside and outside of the United States from which you may access the nuvoTV website.</p>

<p>We require users to respect our copyrights, trademarks, and other intellectual property rights and those of others, including other users. On notice, we will act expeditiously to remove content on the nuvoTV website that infringes the copyright rights of others and will disable the access to the nuvoTV website and its services of anyone who uses them to repeatedly to infringe the intellectual property rights of others. Specific procedures to notify us about copyright infringement can be found on the <b>Notice and Procedure for Making Claims of Copyright Infringement</b>, as described in section 9 below.</p>

<p>The various trademarks, service marks, show names, character names, logos, and other distinctive identifications ("marks") on or of the nuvoTV website are the intellectual property of and proprietary to nuvoTV, its Affiliates, its or their Advertisers, suppliers and others with whom these entities may do business. You have no right to use any of these marks or any confusingly similar marks for any purpose without the express prior written consent of nuvoTV.</p>

<p><b>7. FORUMS AND POSTINGS </b><br>
The nuvoTV website contains forum services, web communities, and other message and communication facilities ("Forums") that may provide you and other users an opportunity to submit, upload, post, display, transmit and/or exchange information, ideas, opinions, information, files, messages, transmissions and nuvoTV Materials with other users and/or with us and these are referred to in this Agreement as a "Post" or "Posting."</p>

<p>nuvoTV reserves the right at all times, but does not have the obligation, to edit, refuse to post, or to remove any Posting, in whole or part, that nuvoTV deems inappropriate for inclusion in the Forums, for any reason or for no reason. Forums are public and not private and you should assume your Postings may be read by others, with or without your knowledge or permission. Although a particular Forum may have a policy of limited membership or access, nuvoTV disclaims all liability if unauthorized persons obtain access to the Forum. <b>You acknowledge that you use the nuvoTV Forums is at your own risk and you should not disclose or make available your personal information in any Posting or in any Forum. </b><br>
You use the Forums solely at your own risk and nuvoTV neither endorses nor controls user Postings in the Forums, and nuvoTV assumes no duty to monitor or endorse Postings within the Forums, nor does nuvoTV represent or guarantee the truthfulness, accuracy or reliability thereof or that any Posting complies with the terms or conditions of this Agreement, and you should not assume that any Posting is true, accurate or reliable.</p>

<p>You understand, acknowledge and agree that Postings originating from any User ID are the sole responsibility of the individual associated with that User ID. This means that you, and not nuvoTV, are entirely responsible for the consequences of all your Postings on the Forums or otherwise on the nuvoTV website. Postings do not reflect the views of nuvoTV or any Affiliates or advertisers. In no event shall nuvoTV or any Affiliates or advertisers have or be construed to have any responsibility or liability for or in connection with any Posting whatsoever; provided, however, if we determine, in our sole discretion and judgment, that any Posting does or may violate any of the terms of this Agreement, violates any law or is otherwise objectionable, we reserve the right, at any time and without limiting any and all other rights we may have under this Agreement, at law or in equity, to: (a) refuse to allow you to Post; (b) remove and delete Postings; (c) revoke your right to use the Forums and the nuvoTV website; and/or (d) use any technological, legal, operational or other means available to us to enforce the provisions of this Agreement, including, without limitation, blocking specific IP addresses or deactivating your registration on nuvoTV and/or the Forums.</p>

<p>If a Posting originates from you or your User ID, you hereby agree that: <br>
(a) you are placing the Posting in the public domain without reservation of any rights or further control over the Posting or its use and you specifically authorize the nuvoTV website and Affiliates to use such Posting in whole or in part, throughout the universe, and you are granting nuvoTV and its Affiliates a royalty-free, perpetual, irrevocable, unrestricted, unconditional, non-exclusive license to use, reproduce, modify, publish, edit, adapt, create derivative works from, translate, distribute, perform, display and otherwise exploit such Posting and all elements thereof alone or as part of other works in any form, media, or technology, whether now known or hereafter developed or discovered, and to license and sub-license such rights through multiple tiers of sub-licenses, all without any notification or obligation to you, of compensation, attribution or otherwise; <br>
(b) you represent and warrant that (i) the Posting is original to you or fully cleared for use as contemplated herein, (ii) the Posting does and will not, in any way, violate or breach any of the terms of this Agreement, (iii) the Posting does not contain libelous, tortious, or otherwise unlawful information, infringe or violate any copyright or other right, or contain any matter the publication or sale of which will violate any law, regulation or other governmental requirement or restriction, (iv) the Posting is not obscene or in any other manner unlawful, (v) the Posting shall not be damaging or injurious to nuvoTV, any Affiliates or any user, and (vi) we shall not be required to pay or incur any sums to any person or entity as a result of our use or exploitation of the Posting; <br>
(c) if your Posting incorporates the name, logo, brand, service or trademark, voice, likeness or image of any person, firm or enterprise, you specifically represent and warrant that you have the right to place such Posting in the public domain and grant nuvoTV and Affiliates the right to use such Posting as described above; and <br>
(d) we have the right to delete, re-format and/or change your Posting in any manner that we may determine (although you will not be responsible for any such changes made).</p>

<p>Your Posting may incorporate links to your content on third party sites, such as your MySpace user page, provided that all such links comply with (i) the nuvoTV Terms of Use; and (ii) the terms of use of the applicable third party site. <br>
The amount of storage space on the nuvoTV website per user is limited and some Postings may not be processed due to space constraints or outbound message limitations. You understand, acknowledge and agree we assume no responsibility for deletion of Postings or any failure to store, receive or deliver Postings in a timely manner or at all or as to any other matter relating to Postings. Posting is for noncommercial purposes only and you may not Post in any manner which does or is intended to promote or generate revenue for any business enterprise or commercial activity.</p>

<p><b>8. RULES OF CONDUCT </b><br>
It is a condition of your use of the nuvoTV website that you abide by all applicable local, state, national laws and regulations and, in some cases, international treaties. You are solely responsible for all activities, acts and omissions that occur in, from, through or under your User ID. You shall not use, allow, or enable others to use the nuvoTV website, or knowingly condone use of the nuvoTV website by others, in any manner that is, attempts to, or might: <br>
- affect nuvoTV adversely or reflect negatively on us, the nuvoTV website, our goodwill, name or reputation or cause duress, distress or discomfort to us or anyone else, or discourage any person, firm or enterprise from using all or any portion, features or functions of the nuvoTV website, or from advertising, linking or becoming a supplier to us in connection with the nuvoTV website; <br>
- be defamatory, libelous, indecent, vulgar or obscene, pornographic, sexually explicit, racially, culturally, or ethnically offensive, harmful, harassing, intimidating, threatening, hateful, discriminatory, or abusive, or which may or may appear to impersonate anyone other than yourself; <br>
- send or result in the transmission of spam, junk e-mail, chain letters, duplicative or unsolicited messages, or so-called "spamming" and "phishing"; <br>
- be used for commercial or business purposes, including, without limitation, advertising, marketing or offering goods or services, whether or not for financial or any other form of compensation or through linking with any other website or web pages; <br>
- transmit, distribute or upload programs or material that contain malicious code, such as viruses, time bombs, cancel-bots, worms, Trojan horses, spyware, or other potentially harmful programs or other material or information; <br>
- forge any TCP/IP packet header or part of the header information in any e-mail or newsgroup posting for any reason;<br>
- violate any laws, regulations (including, without limitation, laws regarding the transmission of technical data or software exported from the United States), judicial or governmental order, any treaties or violate or infringe upon any intellectual property rights, rights of publicity or privacy, or any other rights of ours or of any other person, firm or enterprise; <br>
- gain unauthorized access to the nuvoTV website, other users' accounts, names, User IDs, personally identifiable information or other computers, websites or pages, connected or linked to the nuvoTV website or to use the nuvoTV website in any manner which violates or is inconsistent with the terms and conditions of this Agreement; <br>
- modify, disrupt, impair, alter or interfere with the use, features, functions, operation or maintenance of the nuvoTV website or the rights or use and enjoyment of the nuvoTV website by any other person, firm or enterprise; or <br>
- collect, obtain, compile, gather, transmit, reproduce, delete, revise, view or display any material or information, whether personally identifiable or not, posted by or concerning any other person, firm or enterprise, in connection with their or your use of the nuvoTV website, unless you have obtained the express, prior permission of such other person, firm or enterprise to do so.</p>

<p><b>9. VIOLATIONS OF TERMS AND COPYRIGHT INFRINGEMENT CLAIMS </b><br>
If you believe that any nuvoTV Materials on the nuvoTV website (including, without limitation, any Posting) violates any of the terms or conditions of this Agreement, please send us a message about it at <a href="mailto:feedback@mynuvotv.com">feedback@mynuvotv.com</a>. We cannot guarantee that we will respond to your message, and we reserve the right to take or refrain from taking any or all steps available to us once we receive any such message. <br>
If you believe the nuvoTV website contains elements that infringe your copyrights in your work, please follow these instructions:<br>
Notice and Procedure for Making Claims of Copyright Infringement.</p>

<p>Pursuant to Title 17, United States Code, Section 512(c)(2), all notifications of claimed copyright infringement on the nuvoTV website should be sent ONLY to our Designated Agent. The following information is provided solely for notifying nuvoTV that your copyrighted material may have been infringed.</p>

<p>DO NOT SEND ANY INQUIRIES UNRELATED TO COPYRIGHT INFRINGEMENT (e.g., REQUESTS FOR TECHNICAL ASSISTANCE OR CUSTOMER SERVICE, REPORTS OR E-MAIL ABUSE, etc.) TO THE CONTACT LISTED BELOW. YOU WILL NOT RECEIVE A RESPONSE IF SENT TO THAT CONTACT.</p>

<p>WE CAUTION YOU THAT UNDER FEDERAL LAW, IF YOU KNOWINGLY MISREPRESENT THAT ONLINE CONTENT IS INFRINGING, YOU MAY BE SUBJECT TO HEAVY CIVIL PENALTIES. THESE INCLUDE MONETARY DAMAGES, COURT COSTS, AND ATTORNEYS FEES INCURRED BY US, BY ANY COPYRIGHT OWNER, OR BY ANY COPYRIGHT OWNER'S LICENSEE THAT IS INJURED AS A RESULT OF OUR RELYING UPON YOUR MISREPRESENTATION. YOU MAY ALSO BE SUBJECT TO CRIMINAL PROSECUTION FOR PERJURY.</p>

<p>Written notification must be submitted to the following Designated Agent: S&Iacute; TV, Inc.<br>
Agent Designated to Receive Notification of Claimed Infringement: Manager, Business Affairs <br>
Full Address of Designated Agent to Which Notification Should be Sent:<br>
700 N Central Ave<br>
Glendale, CA 91203</p>
<p><br>
Telephone Number of Designated Agent: (323) 256-8900</p>
<p><br>
Facsimile Number of Designated Agent: (323) 256-9888</p>
<p><br>
E-mail Address of Designated Agent: <a href="mailto:copyright@mynuvotv.com">copyright@mynuvotv.com</a></p>

<p>Under Title 17, United States Code, Section 512(c)(3)(A), the Notification of Claimed Infringement must include the following:</p>
<p><br>
(1) An electronic or physical signature of the owner or of the person authorized to act on behalf of the owner of the copyright interest; <br>
(2) Identification of the copyrighted work (or works) that you claim has been infringed; <br>
(3) A description of the material that you claim is infringing, and the location where the original or an authorized copy of the copyrighted work exists (for example, the URL of the page of the website where it is lawfully posted; the name, edition and pages of a book from which an excerpt was copied, etc.); <br>
(4) A clear description of where the infringing material is located on our website, including as applicable its URL, so that we can locate the material; <br>
(5) Your name, address, telephone number, and e-mail address; <br>
(6) A statement that you have a good-faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and <br>
(7) A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf.</p>

<p><b><br>
10. ADVERTISING</b> <br>
The nuvoTV website contains various forms of advertisements of our sponsors. As a result of this, you may communicate with, receive communications from, be re-directed to, interact with, or participate in or use the services or obtain goods and services of or from, third parties such as our advertisers, sponsors, or promotional partners ("Advertisers"). All such interaction is strictly and solely between you and the Advertiser involved and nuvoTV is not be responsible or liable to you in any way in connection with these activities or transactions (including, without limitation, any representations, warranties, covenants, contracts or other terms or conditions that may exist between you and the Advertiser or any goods or services you may obtain from any Advertiser).</p>

<p><b>11. CONTESTS AND PROMOTIONS </b><br>
From time to time, nuvoTV's, the Affiliates', or the nuvoTV website's service providers, suppliers, and Advertisers may conduct promotions on or through the nuvoTV website, including, without limitation, auctions, contests and sweepstakes ("Promotions"). Each Promotion may have additional rules which will be posted or otherwise made available to you and, for purposes of each Promotion, will be deemed incorporated into and form a part of this Agreement; provided, however, if there is any conflict between the rules for any particular Promotion and these Terms of Use, the rules shall govern for that particular Promotion.</p>

<p><b>12. LINKS TO OTHER SITES </b><br>
The appearance, availability, or your use of URLs or hyperlinks referenced or included anywhere on the nuvoTV website or any other form of link or re-direction of your connection to, with or through the nuvoTV website, does not constitute an endorsement by, nor does it incur any obligation, responsibility or liability on the part of nuvoTV, its Affiliates or any of its or their respective officers, directors, employees, agents, representatives, licensors, suppliers, and service providers, successors and permitted assigns. We do not verify, endorse, or have any responsibility for, any such third party sites, their business practices, their privacy policies, or any goods or services associated with or obtained in connection with any such site, whether nuvoTV's or any Affiliates' logo or sponsorship identification is on the third party site as part of a co-branding or promotional arrangement. If any third party site obtains or collects Personal Information from you, such collection is governed by the privacy policy of such third party site, and in no event shall we assume or have any responsibility or liability. Please read our nuvoTV Privacy Policy, which describes how nuvoTV collects and uses your Personal Information and co-branding relationships.</p>

<p><b>13. TERMINATION OF YOUR REGISTRATION </b><br>
You may cancel your registration and User ID at any time and for any reason by sending an e-mail to <a href="mailto:termination@mynuvotv.com">termination@mynuvotv.com</a> with your username, password, and e-mail address and requesting termination of your registration. nuvoTV may terminate your use of and registration on the nuvoTV website, at any time and for any reason, with or without cause, without prior notice to you and without any liability or further obligation of any kind whatsoever to you or any other party.</p>

<p><b>14. DISCLAIMERS </b><br>
THE NUVOTV WEBSITE(S) AND ALL SERVICES, FEATURES, FUNCTIONS, CONTENT, PRODUCTS AND CAPABILITIES ARE MADE AVAILABLE ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY REPRESENTATION OR WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ALL WARRANTIES OF MERCHANTABILITY, OF FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN ADDITION, NUVOTV MAKES AND PROVIDES NO GUARANTY OR ASSURANCE THE NUVOTV WEBSITE OR ANY CONTENT WILL OPERATE WITHOUT INTERRUPTION OR THAT ALL SERVICES, PRODUCTS, FEATURES, FUNCTIONS, PRODUCTS, CONTENT OR OPERATIONS WILL BE AVAILABLE OR PERFORM AS DESCRIBED OR AT ANY PARTICULAR TIME OR TIMES.</p>

<p>Without limiting the foregoing, we are not responsible or liable for any malicious code, delays, inaccuracies, errors, or omissions arising out of your use of the nuvoTV website. You acknowledge and agree that you are assuming the entire risk of using the nuvoTV website and the services, features and functions of and/or associated with the nuvoTV website.</p>

<p>YOU UNDERSTAND AND AGREE THAT, TO THE FULLEST EXTENT PERMISSIBLE BY LAW, NEITHER NUVOTV, ITS AFFILIATES, OR ITS OR THEIR RESPECTIVE SUCCESSORS AND ASSIGNS, NOR ANY OF ITS OR THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, LICENSORS, REPRESENTATIVES, SERVICE PROVIDERS, ADVERTISERS, OR SUPPLIERS, SHALL BE LIABLE FOR ANY LOSS OR DAMAGE, OF ANY KIND, DIRECT OR INDIRECT, IN CONNECTION WITH OR ARISING FROM USE OF THE NUVOTV WEBSITE OR RELATED TO THIS AGREEMENT, INCLUDING, BUT NOT LIMITED TO, COMPENSATORY, CONSEQUENTIAL, INCIDENTAL, INDIRECT, SPECIAL OR PUNITIVE DAMAGES, REGARDLESS OF THE FORM OF ACTION OR THE BASIS OF THE CLAIM AND EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. Some jurisdictions do not allow for the exclusion of certain warranties or certain limitations on damages and remedies, accordingly some of the exclusions and limitations described in this Agreement may not apply to you.</p>

<p>THE WEBSITE IS MAINTAINED ON SERVERS IN THE UNITED STATES INTENDED FOR USERS AND USE OF THE WEBSITE THAT IS NOT RESTRICTED OR PROHIBITED BY LAW OR REGULATION. NUVOTV DISCLAIMS ALL LIABILITY FOR ANY USE NOT SPECIFICALLY AUTHORIZED OR THAT IS IN VIOLATION OF THIS AGREEMENT OR THE LAWS OR REGULATIONS THAT MAY APPLY TO YOU IN ANY JURISDICTION OR COUNTRY.</p>

<p><b><br>
15. INDEMNIFICATION </b><br>
You agree to indemnify, defend (at nuvoTV's election) and hold harmless nuvoTV, its Affiliates and its and their respective officers, directors, employees, agents, licensors, representatives, Advertisers, service providers and suppliers from and against any and all claims, actions, losses, expenses, damages and costs (including, without limitation, reasonable attorneys' fees), resulting from any breach or violation of this Agreement by you, or resulting from your Postings or any nuvoTV Materials you provide, submit or make available on or through the nuvoTV website or your unauthorized use of any nuvoTV Materials. nuvoTV reserves the right to assume, at its expense, the exclusive defense and control of any such claim or action and all negotiations for settlement or compromise, and you agree to fully cooperate with nuvoTV in the defense of any such claim, action, settlement or compromise negotiations, as requested by nuvoTV.</p>

<p><b>16. APPLICABLE LAW AND OTHER TERMS </b><br>
This Agreement, including, without limitation, the nuvoTV Privacy Policy, the <b>User Content Submission Agreement</b>, any rules governing any particular contest or promotion and any additional terms and conditions that apply to your use of any specific services, features and functions, as well as any other documents, policies and provisions we refer to in any of the foregoing, all of which are hereby incorporated by this reference, contains the entire understanding and agreement between you and nuvoTV and supersedes any and all prior, inconsistent or other understandings relating to the nuvoTV website and your use of the nuvoTV website. This Agreement cannot be modified, changed or terminated, except as specifically described in Section 4 above.</p>

<p>If any provision of this Agreement is held to be illegal, invalid or unenforceable, this will not affect any other provisions and this Agreement will be deemed amended to the extent necessary to make it legal, valid and enforceable. Any provision which must survive in order to allow us to enforce its meaning shall survive termination of this Agreement; provided, however, no action arising out of this Agreement or your use of the nuvoTV website, regardless of form or the basis of the claim, may be brought by you more than one year after the cause of action has arisen (or if multiple causes, from the date the first such cause arose).</p>

<p>You agree that the nuvoTV website shall be deemed solely based in California and that the nuvoTV website shall be deemed a passive website that does not give rise to personal jurisdiction over nuvoTV, either specific or general, in jurisdictions other than California. This Agreement and your use of the nuvoTV website shall be governed by, construed and enforced in accordance with the substantive laws of the United States of American and the State of California applicable to contracts made, executed and wholly performed in that State, and, for the purposes of any and all legal or equitable actions, you specifically agree and submit to the exclusive jurisdiction and venue of the State and Federal Courts situated in the State of California and County of Los Angeles and agree you will not object to such jurisdiction or venue on the grounds of lack of personal jurisdiction, forum non conveniens or otherwise; provided, however, that notwithstanding the foregoing, you agree that nuvoTV has the right to commence and prosecute an action against you in connection with this Agreement, in your home jurisdiction. Either nuvoTV or you may demand that any dispute between the nuvoTV website and you about or involving the nuvoTV website must be settled by arbitration utilizing the dispute resolution procedures of the American Arbitration Association (AAA) in Los Angeles, California, USA, provided that the foregoing shall not prevent nuvoTV from seeking injunctive relief in a court of competent jurisdiction. To the extent it may be applicable, you agree to opt out from and expressly exclude any applicability of the Uniform Computer Information Transactions Act.</p>

<p>IN ANY ACTION OR PROCEEDING COMMENCED TO ENFORCE ANY RIGHT OR OBLIGATION OF THE PARTIES UNDER THIS AGREEMENT, YOUR USE OF THE NUVOTV WEBSITE(s) OR WITH RESPECT TO THE SUBJECT MATTER HEREOF, YOU HEREBY WAIVE ANY RIGHT YOU MAY NOW HAVE OR HEREAFTER POSSESS TO A TRIAL BY JURY.</p>

<p>A printed version of this Agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this Agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</p>
</div>
	    <div class="taxonomy"></div>
      </div>
	</div>
EOCONTENT;

*/

?>